config/routes.rb
RottenMangoes::Application.routes.draw do

  get "reviews/new"
  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  root to: 'movies#index'

  namespace :admin do
    resources :users
  end

  

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews, dependent: :destroy

  validates_presence_of :title, :director, :description, :poster_image_url, :release_date
  validates :runtime_in_minutes, numericality: { only_integer: true }
  validate :release_date_is_in_the_past

  mount_uploader :poster_image_url, ImageUploader

  scope :under_90mins,         -> { where("runtime_in_minutes < 90") }
  scope :between_90and120mins, -> { where("runtime_in_minutes BETWEEN 90 AND 120") }
  scope :over_120mins,         -> { where("runtime_in_minutes > 120") }

  def self.search_movies(keyword)
    where("title LIKE ? OR director LIKE ?", "%#{keyword}%", "%#{keyword}%")
  end

  def review_average
    reviews.sum(:rating_out_of_ten)/reviews.size
  end

  protected

  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user,
        presence: true

  validates :movie,
    presence: true

  validates :text,
    presence: true

  validates :rating_out_of_ten,
    numericality: { only_integer: true }
  validates :rating_out_of_ten,
    numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten,
    numericality: { less_than_or_equal_to: 10 }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  has_secure_password

  before_destroy :send_goodbye_email

  validates :email, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, presence: true, length: { in: 6..20 }, on: :create
  validates :password_confirmation, presence: true

  def full_name
    "#{firstname} #{lastname}"
  end

  private

  def send_goodbye_email
    UserMailer.goodbye_email(self).deliver_now
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :check_authorization

  protected

  def check_authorization
    unless current_user.is_admin
      flash[:error] = "Unauthorized access"
      redirect_to root_path
      false
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController

  def index
    @users = User.all.page(params[:page]).per(10).order(:id)
  end

  def show
    user_selected
    @reviews = @user.reviews
  end

  def edit
    user_selected
  end

  def update
    user_selected
    @user.update_attributes(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "User account updated successfully"
    else
      render :edit
    end
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save!
      
      redirect_to admin_users_path, notice: "User successfully created!"
    else
      render :new
    end
  end

  def destroy
    user_selected
    @user.destroy
    redirect_to admin_users_path
  end

  protected

  def user_selected
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :is_admin)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
    if params[:search_movies] != "" 
      @movies = @movies.search_movies(params[:search_movies])
    end
    if params[:search_duration] != ""
      case params[:search_duration]
      when "Under 90 minutes"
        @movies = @movies.under_90mins
      when "Between 90 and 120 minutes"
        @movies = @movies.between_90and120mins
      when "Over 120 minutes"
        @movies = @movies.over_120mins
      end
    end
    if @movies.size == 0
      flash[:notice] = "DB migrate"
      @movies = Movie.all
    else
      @movies
    end
  end

  def show
    movie_selected
  end

  def new
    @movie = Movie.new
  end

  def edit
    movie_selected
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    movie_selected

    if @movie.update_attributes(movie_params)
      redirect_to @movie
    else
      render :edit
    end
  end

  def destroy
    movie_selected
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_selected
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description, :remote_poster_image_url_url
    )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :restrict_access
  before_filter :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully!"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :is_admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<% if @user.id.nil? %>
  <% custom_url = admin_users_path %>
<% else %>
  <% custom_url = edit_admin_user_path(@user) %>
<% end %>
<%= form_for @user, url: custom_url do |f| %>
<div>
  <%= f.label :firstname %>
  <%= f.text_field :firstname %>
</div>
<div>
  <%= f.label :lastname %>
  <%= f.text_field :lastname %>
</div>
<div>
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>
<div>
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>
<div>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>
<div>
  <%= f.label :is_admin %>
  <%= f.check_box :is_admin %>
</div>
<div>
  <%= f.submit "Create User" %>
</div>
<% end %>

app/views/admin/users/edit.html.erb
<%= link_to "Main Admin Page", admin_users_path %>

<h3>Edit user</h3>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Admin User Management</h1>
<%= link_to "Create new user", new_admin_user_path %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>id</th>
      <th>full name</th>
      <th>email</th>
      <th>admin</th>
      <th>edit</th>
      <th>view</th>
      <th>delete</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.full_name %></td>
        <td><%= user.email %></td>
        <td><%= user.is_admin ? "Admin" : "User" %></td>
        <td><%= link_to "edit", edit_admin_user_path(user) %></td>
        <td><%= link_to "view", admin_user_path(user) %></td>
        <td><%= link_to "delete", admin_user_path(user), method: :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
      
    <% end %>
  </tbody>

</table>

<hr>

<%= paginate @users %>

app/views/admin/users/new.html.erb
<%= link_to "Main Admin Page", admin_users_path %>
<h3>Create a new user</h3>

<%= render 'form' %>

app/views/admin/users/show.html.erb
<%= link_to "Main Admin Page", admin_users_path %>

<h3>Full name: <%= @user.full_name %> (<%= link_to "edit", edit_admin_user_path(@user) %>)</h3>
<p>Email: <%= @user.email %></p>
<p>Date joined: <%= formatted_date(@user.created_at) %></p>

<hr>

<h4>Reviews by user</h4>

<% @reviews.each do |review| %>
  <p><%= review.movie.title %></p>
  <p><%= review.rating_out_of_ten %></p>
  <p><%= review.text %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= link_to current_user.full_name, user_path(current_user) %> ( <%= link_to "Log Out", session_path("current"), method: :delete %> <%= link_to "Admin Page", admin_users_path if current_user.is_admin? %>)
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <div class="row">
    <%= yield %>
  </div>
  <div class="row">
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: {multipart: true} do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </div>
  <div>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div>
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes %>
  </div>
  <div>
    <%= f.label :poster_image_url %><br>
    <%= f.file_field :poster_image_url %>

<!--     <% if f.object.poster_image_url? %>
      <% image_tag f.object.poster_image_url.thumb.url %>
      <% f.label :remove_poster_image_url %>
      <% f.check_box :remove_poster_image_url %>
    <% end %> -->
    
  </div>
  <div>
    <%= f.label :remote_poster_image_url_url %><br>
    <%= f.text_field :remote_poster_image_url_url %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div class="col-xs-3">
  <p><%= image_tag movie.poster_image_url_url(:thumb) %></p>
  <p><%= link_to movie.title, movie %></p>
  <p><%= formatted_date(movie.release_date) %></p>
  <p><%= movie.director %> | <%= movie.runtime_in_minutes %></p>
  <p>average: <%= movie.reviews.size > 0 ? movie.review_average : "-" %>/10</p>
  <p><%= movie.description %></p>
</div>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie</h2>
<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Rotten Mangoes</h1>

<%= form_tag(root_path, method: "get") do %>
  <%= label_tag(:search_movies, "Keyword: ") %>
  <%= text_field_tag(:search_movies) %>
  <%= select_tag(:search_duration, 
    "<option></option>
      <option>Under 90 minutes</option>
      <option>Between 90 and 120 minutes</option>
      <option>Over 120 minutes</option>".html_safe) %>
  <%= submit_tag("Search") %>
<% end %>



<hr>
<%= link_to "Submit a movie", new_movie_path %>
<hr>
<% @movies.each do |movie| %>
  <%= render partial: "movie", locals: { movie: movie } %>
<% end %>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>

<h2>Submit a movie</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>

<%= image_tag(@movie.poster_image_url_url(:thumb).to_s) %>
<%= image_tag(@movie.poster_image_url) %>

<p><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, data: {confirm: "You sure?"} %>)</p>
<p><%= formatted_date(@movie.release_date) %></p>
<p><%= @movie.director %> | <%= @movie.runtime_in_minutes %></p>
<p><%= @movie.description %></p>
<p>average: <%= @movie.reviews.size > 0 ? @movie.review_average : "-" %>/10</p>

<hr>

<p>Reviews of <em><%= @movie.title %></em></p>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <p><%= link_to review.user.full_name, user_path(review.user) %> </p>

    
    <small>- <%= review.user.full_name %></small><br/>
  <% end %>
    <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p>
<% end %>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>

  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :text %><br/>
    <%= f.text_area "text" %>
  </div>

  <div>
    <%= f.label :rating_out_of_ten %><br/>
    <%= f.number_field :rating_out_of_ten %>
  </div>
  <div><%= f.submit "Submit" %></div>

<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/show.html.erb
<%= link_to "Home", root_path %>
<!--  (<%= link_to "edit", edit_admin_user_path(@user) %>) -->
<h3>Full name: <%= @user.full_name %></h3>
<p>Email: <%= @user.email %></p>
<p>Date joined: <%= formatted_date(@user.created_at) %></p>

<hr>

<h4>Reviews by user</h4>

<% @reviews.each do |review| %>
  <p>movie: <%= review.movie.title %></p>
  <p>rating: <%= review.rating_out_of_ten %>/10</p>
  <p>review: <%= review.text %></p>
  <hr>
<% end %>